# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item_supply',
            name='date_supplied',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
